version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: sublow_postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sublow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sublow_net

  redis:
    image: redis:alpine
    container_name: sublow_redis
    ports:
      - '6379:6379'
    networks:
      - sublow_net

networks:
  sublow_net:
    driver: bridge

volumes:
  postgres_data:
